# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markericon',
            name='lat',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='markericon',
            name='lon',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
